allowed.origins:
  http://localhost:3000,
  http://localhost:8080

# If you want it all
#logging:
#  level:
#    root: DEBUG

#Token validation
no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}

DB_HOST: localhost
DB_USERNAME: klage
DB_PASSWORD: klage

PDL_BASE_URL: https://pdl-api.dev-fss.nais.io/graphql
SERVICE_USER_USERNAME: srvklage-dittnav
SERVICE_USER_PASSWORD: OVERRIDE_IN_RUNTIME

CLAM_AV_URL: http://clamav.nais.svc.nais.local/scan

FILE_BASE_URL: http://localhost:7080

STS_APIKEY: test
PDL_APIKEY: test

AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
AZURE_APP_CLIENT_ID: 9ba0e760-d28c-44d2-8cae-8a1dc9b4584f
AZURE_APP_CLIENT_SECRET: test

SLACK_URL: http://localhost
SLACK_CHANNEL_ID: test
NAIS_CLUSTER_NAME: local
NAIS_NAMESPACE: klage

DRAFT_CLEANUP_CRON: 0 0 9,12,16 * * MON-FRI
MAX_DRAFT_AGE_IN_DAYS: 180