allowed.origins:
  http://localhost:3000,
  http://localhost:8080

# If you want it all
#logging:
#  level:
#    root: DEBUG

#Token validation
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookiename: selvbetjening-idtoken
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}

DB_HOST: localhost
DB_USERNAME: klage
DB_PASSWORD: klage

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_CLIENTID: klage-dittnav-api
KAFKA_TOPIC: aapen-klager-klageOpprettet

PDL_BASE_URL: http://localhost:7000/graphql
SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: srvklage-dittnav
SERVICE_USER_PASSWORD: OVERRIDE_IN_RUNTIME

CLAM_AV_URL: http://clamav.nais.svc.nais.local/scan

FILE_BASE_URL: http://localhost:7080

STS_APIKEY: test
PDL_APIKEY: test

AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
AZURE_APP_CLIENT_ID: 9ba0e760-d28c-44d2-8cae-8a1dc9b4584f
AZURE_APP_CLIENT_SECRET: test

SLACK_URL: http://localhost
SLACK_CHANNEL_ID: test
NAIS_CLUSTER_NAME: local

KLAGE_FILE_API_CLIENT_ID: 64245dd5-e178-495e-9af2-5d8961690437

LOGINSERVICE_IDPORTEN_DISCOVERY_URL: http://localhost


