#Token validation
no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
    cookiename: selvbetjening-idtoken

DB_HOST: localhost
DB_USERNAME: klage
DB_PASSWORD: klage

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_CLIENTID: klage-dittnav-api
KAFKA_TOPIC: aapen-klager-klageOpprettet

PDL_BASE_URL: http://localhost:7000/graphql
SECURITY_TOKEN_SERVICE_REST_URL: http://localhost:8088
SERVICE_USER_USERNAME: srvklage-dittnav
SERVICE_USER_PASSWORD: OVERRIDE_IN_RUNTIME

CLAM_AV_URL: http://clamav.nais.svc.nais.local/scan

STS_APIKEY: test
PDL_APIKEY: test