ingresses:
  - https://klage-dittnav-api.intern.dev.nav.no
externalHosts:
  - pdl-api.dev-fss-pub.nais.io
  - klage-fss-proxy.dev-fss-pub.nais.io
  - safselvbetjening.dev-fss-pub.nais.io
springProfile: dev

envs:
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"
kafka_pool: nav-dev

db_tier: db-f1-micro
db_type: POSTGRES_17
db_high_availability: false

max_replicas: 2