externalHosts:
  - pdl-api.prod-fss-pub.nais.io
  - klage-fss-proxy.dev-fss-pub.nais.io
  - safselvbetjening.prod-fss-pub.nais.io
springProfile: prod
envs:
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx4096m"
kafka_pool: nav-prod

db_tier: db-custom-1-3840
db_type: POSTGRES_17
db_high_availability: true

max_replicas: 4